package com.sample.rules
 
import com.sample.Klima;
 
rule "Uslov 1"
    when
        k : Klima(kvadraturaStana <= 50 && viseProstorija == false && snagaKlime == 0)
    then
        k.setSnagaKlime(9000);
        update(k);
end

rule "Uslov 2"
    when
        k : Klima(kvadraturaStana <= 50 && viseProstorija == true && snagaKlime == 0)
    then
        k.setSnagaKlime(12000);
        update(k);
end

rule "Uslov 3"
    when
        k : Klima(kvadraturaStana > 50 && kvadraturaStana < 75 && viseProstorija == false && snagaKlime == 0)
    then
        k.setSnagaKlime(12000);
        update(k);
end

rule "Uslov 4"
    when
        k : Klima(kvadraturaStana > 50 && kvadraturaStana < 75 && viseProstorija == true && snagaKlime == 0)
    then
        k.setSnagaKlime(18000);
        update(k);
end

rule "Uslov 5"
    when
        k : Klima(kvadraturaStana >= 75 && snagaKlime == 0)
    then
        k.setSnagaKlime(18000);
        update(k);
end

rule "Uslov 6"
    when
        k : Klima(viseProstorija == true && mogucaUgradnja == false && tipKlime == "obicna")
    then
        k.setTipKlime("pokretni");
        update(k);
end

rule "Uslov 7"
    when
        k : Klima(viseProstorija == false && mogucaUgradnja == false && tipKlime == "obicna")
    then
        k.setTipKlime("prozorski");
        update(k);
end

rule "Uslov 8"
    when
        k : Klima(inverter == false && (koriscenje == "podjednako" || koriscenje == "pretezno"))
    then
        k.setInverter(true);
        update(k);
end

rule "Uslov 9"
    when
        k : Klima(inverter == true && koriscenje == "rijetko")
    then
        k.setInverter(false);
        update(k);
end

rule "Uslov 10"
    when
        k : Klima(inverter == false && malaTemperatura == true)
    then
        k.setInverter(true);
        update(k);
end