package com.sample.rules
 
import com.sample.Klijent;
 
rule "Uslov 1"
    when
        k : Klijent(vozackaB == false && izdavanje == true)
    then
        k.setIzdavanje(false);
        update(k);
end

rule "Uslov 2"
    when
        k : Klijent(vozackaB == true && (godine < 19 || godineVozacke < 1) && izdavanje == true)
    then
        k.setIzdavanje(false);
        update(k);
end

rule "Uslov 3"
    when
        k : Klijent(vozackaB == true && godineVozacke < 5 && izdavanje == true && depozit == false)
    then
        k.setDepozit(true);
        update(k);
end

rule "Uslov 4"
    when
        k : Klijent(vozackaB == true && izdavanje == true && godineVozacke <= 3 && depozit == true && iznosDepozita == 0)
    then
        k.setIznosDepozita(50);
        update(k);
end

rule "Uslov 5"
    when
        k : Klijent(vozackaB == true && izdavanje == true && godineVozacke > 3 && godineVozacke < 5 && depozit == true && iznosDepozita == 0)
    then
        k.setIznosDepozita(30);
        update(k);
end

rule "Uslov 6"
    when
        k : Klijent(vozackaB == true && izdavanje == true && godineVozacke <= 2 && izdavanje == true && kategorije.isEmpty())
    then
        k.getKategorije().add("A");
        k.getKategorije().add("B");
        update(k);
end

rule "Uslov 7"
    when
        k : Klijent(vozackaB == true && izdavanje == true && godineVozacke > 2 && godineVozacke < 5 && izdavanje == true && kategorije.isEmpty())
    then
        k.getKategorije().add("A");
        k.getKategorije().add("B");
        k.getKategorije().add("C");
        k.getKategorije().add("D");
        update(k);
end

rule "Uslov 8"
    when
        k : Klijent(vozackaB == true && izdavanje == true && godineVozacke >= 5 && izdavanje == true && kategorije.isEmpty())
    then
        k.getKategorije().add("A");
        k.getKategorije().add("B");
        k.getKategorije().add("C");
        k.getKategorije().add("D");
        k.getKategorije().add("E");
        k.getKategorije().add("F");
        update(k);
end